name: Reusable workflow main file

on:
 workflow_dispatch:
   inputs:
    PROJECT_CODE:
        description: 'Project code'
        required: true
        default: ''
 
jobs:
 Call-workflow-file-from-same-repo:
  uses: ./.github/workflows/workflowfile1.yml
 Call-from-different-branch:
  uses: darshitsri/reuseable--workflow/.github/workflows/workflowfile2.yml@reusbale-workflow2
