name: Reusable workflow main_1 file

on:
 workflow_dispatch:
jobs:
  call-workflow-in-local-repo:
     strategy:
       matrix:
         code: [335, 343]
         include:
           - code: 335
             name: Titan335
           - code: 343
             name: TItan343
     uses: ./.github/workflows/workflowfile1.yml
     with:
       PROJECT_CODE: ${{ matrix.code }}
       PROJECT_NAME: ${{ matrix.name }}
