name: reusbale workflow file1

on:
  workflow_call:
jobs:
  run1-job1:
   runs-on: ubuntu-latest
   steps:
    - name: output form workflow file1
      run: |
          echo "Product CODE:" ${{ inputs.PROJECT_CODE }}
          echo "Product NAME:" ${{ inputs.PROJECT_NAME }}

